name: Get Hello XR Executable

on:
  workflow_dispatch:

jobs:
  build-sample:
    runs-on: windows-2022

    steps:
      - name: Checkout Full OpenXR Source
        uses: actions/checkout@v4
        with:
          repository: KhronosGroup/OpenXR-SDK-Source # Explicitly pull the full source repo
          submodules: recursive # Recursively grabs Catch2 and all other required files

      - name: Configure CMake
        run: |
          cmake -B build_dir -A x64 -DBUILD_TESTS=ON -DBUILD_LOADER=ON

      - name: Compile Executable
        run: |
          cmake --build build_dir --config Release --target hello_xr

      - name: Upload Hello XR
        uses: actions/upload-artifact@v4
        with:
          name: hello_xr_windows_x64
          path: build_dir/src/tests/hello_xr/Release/hello_xr.exe
